-- 2. adım: kategoriler
-- Supabase SQL Editor'de çalıştır (schema.sql'den sonra).

create table if not exists categories (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  color text not null default '#6366f1',
  inserted_at timestamptz not null default now(),
  -- Aynı kullanıcı aynı ismi iki kez açamasın. Farklı kullanıcılar açabilir.
  unique (user_id, name)
);

alter table categories enable row level security;

-- todos tablosuna kategori bağı.
-- "on delete set null": kategoriyi silersen görevler silinmez, kategorisiz kalır.
-- (Alternatifi "on delete cascade" olurdu ve görevleri de silerdi.)
alter table todos add column if not exists category_id bigint
  references categories on delete set null;

-- Kategoriler de realtime yayınına girsin.
alter publication supabase_realtime add table categories;


-- ============================================================================
-- ALIŞTIRMA: 4 policy'yi sen yaz.
--
-- Kalıbı supabase/schema.sql içindeki todos policy'lerinde birebir var.
-- Aynı mantığı categories için tekrarlaman gerekiyor: select, insert,
-- update, delete -- her biri satırın sahibi olan kullanıcıyla sınırlı.
--
-- İpucu: select/update/delete "using (...)" ile, insert "with check (...)"
-- ile yazılır. Neden farklı olduklarını düşün: biri var olan satırı
-- süzüyor, diğeri yazılmak istenen satırı denetliyor.
--
-- create policy "..." on categories for select using ( ... );
-- create policy "..." on categories for insert with check ( ... );
-- create policy "..." on categories for update using ( ... );
-- create policy "..." on categories for delete using ( ... );
-- ============================================================================
