-- Supabase SQL Editor'de calistir: https://supabase.com/dashboard/project/_/sql/new

create table if not exists todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  task text not null,
  is_complete boolean not null default false,
  inserted_at timestamptz not null default now()
);

alter table todos enable row level security;

create policy "Individuals can view their own todos."
  on todos for select
  using ( (select auth.uid()) = user_id );

create policy "Individuals can create todos."
  on todos for insert
  with check ( (select auth.uid()) = user_id );

create policy "Individuals can update their own todos."
  on todos for update
  using ( (select auth.uid()) = user_id );

create policy "Individuals can delete their own todos."
  on todos for delete
  using ( (select auth.uid()) = user_id );

-- Realtime aboneligi icin: Database > Replication'dan "todos" tablosunu acabilir
-- ya da asagidaki satiri calistirabilirsin (proje zaten "supabase_realtime" publication'i icermiyorsa hata verir).
alter publication supabase_realtime add table todos;
